feat: implement landing page component
BuildForSDG/SmeVest-Frontend pull request #7
Opened 2020-05-11 18:44 UTC by Yasholma

## Description

- Created header component, footer component and home component
- Created unit tests for each of the components
- Installed bootstrap for responsive styling
- Added some rules to eslintrc.js config

Delivers #4 

## How Has This Been Tested?

1. In your terminal, run git clone https://github.com/BuildForSDG/SmeVest-Frontend.git
2. Run cd SmeVest-Frontend
3. Run git fetch origin ft-landing-page
4. Run git checkout origin/ft-landing-page
5. Run yarn install
6. Run yarn start and navigate to http://localhost:1234 on your browser
7. Run yarn test for unit tests

## Screenshots (if applicable, else remove this line / section)
![image](https://user-images.githubusercontent.com/27803089/81598659-92d9b800-93bf-11ea-9032-598b101beaa7.png)

![image](https://user-images.githubusercontent.com/27803089/81598737-ae44c300-93bf-11ea-824d-3123f41f0535.png)

![image](https://user-images.githubusercontent.com/27803089/81598764-b7ce2b00-93bf-11ea-818c-3f29bfc1ff7c.png)

![image](https://user-images.githubusercontent.com/27803089/81598794-c1f02980-93bf-11ea-99a4-cf0bf330132c.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

2020-05-11 20:27 UTC, achingachris reviewed
honestly never worked with react, but I
![Screenshot from 2020-05-11 22-57-42](https://user-images.githubusercontent.com/50122165/81608377-d7288080-93de-11ea-93e4-519ba8bf2fc6.png)
 tried the project and got a building error, either I didn't get the procedure right or some config ain't right

2020-05-11 21:06 UTC, Yasholma commented
> honestly never worked with react, but I
> ![Screenshot from 2020-05-11 22-57-42](https://user-images.githubusercontent.com/50122165/81608377-d7288080-93de-11ea-93e4-519ba8bf2fc6.png)
> tried the project and got a building error, either I didn't get the procedure right or some config ain't right

It has been fixed. eslint was giving me issues. Sorry about that. Just clone the repo again.

2020-05-11 23:13 UTC, Johnny2020Ade reviewed
Good work

2020-05-11 23:14 UTC, Johnny2020Ade submitted a review, later dismissed

2020-05-12 08:03 UTC, ChrisAchinga commented
> > honestly never worked with react, but I
> > ![Screenshot from 2020-05-11 22-57-42](https://user-images.githubusercontent.com/50122165/81608377-d7288080-93de-11ea-93e4-519ba8bf2fc6.png)
> > tried the project and got a building error, either I didn't get the procedure right or some config ain't right
> 
> It has been fixed. eslint was giving me issues. Sorry about that. Just clone the repo again.

okay, let me redo

2020-05-12 11:03 UTC, oyewoas requested changes

2020-05-12 11:03 UTC, oyewoas commented on src/components/Footer/Footer.js
> +    <p className="Copyright">&copy; Copyright 2020 SmeVest. All rights reserved. </p>
Welldone @Yasholma  this is nice, however i am wondering if we can set the year in such a way that i updates automatically, you can have a constant like `const date = new Date();` declared, then replace **2020** with `{date.getFullYear()}` in the `Footer Component`

2020-05-12 11:07 UTC, Yasholma commented on src/components/Footer/Footer.js
> +    <p className="Copyright">&copy; Copyright 2020 SmeVest. All rights reserved. </p>
Alright, I will implement that. Should I do it now or during the next PR?

2020-05-12 11:11 UTC, oyewoas commented on src/components/Footer/Footer.js
> +    <p className="Copyright">&copy; Copyright 2020 SmeVest. All rights reserved. </p>
I think you should do that now once and for all since its nothing much

2020-05-12 11:26 UTC, Yasholma commented on src/components/Footer/Footer.js
> +    <p className="Copyright">&copy; Copyright 2020 SmeVest. All rights reserved. </p>
Ok, I just did now.

2020-05-12 14:03 UTC, oyewoas approved these changes

2020-05-12 15:16 UTC, Alasco95 approved these changes
Excellent work

2020-05-12 17:20 UTC, Johnny2020Ade approved these changes

2020-05-12 17:28 UTC, merged